add_newline = true
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
${custom.jujutsu}\
$all"""

# ${custom.jujutsu-closest-bookmarks}\

[aws]
symbol = "  "

[character]
# success_symbol = "[❯](bold purple)"
# vicmd_symbol = "[❮](bold purple)"

[battery]
disabled = true
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = "  "

[directory]
style = "cyan"
read_only = " 🔒"

[direnv]
disabled = true
format = '[$symbol($loaded)(/$allowed)]($style) '
symbol = '◉ '
allowed_msg = ''

[docker_context]
symbol = "  "

[dotnet]
disabled = true

[elixir]
symbol = "  "

[elm]
symbol = "  "

[git_branch]
disabled = false
style = 'purple'
format = 'on [[$symbol](bold $style)$branch(:$remote_branch)]($style) '
only_attached = true

[git_commit]
disabled = true
style = 'purple'
format = 'on [[](bold $style) $hash$tag]($style) '
only_detached = true

[git_state]
disabled = false

[git_status]
disabled = true

[golang]
symbol = "  "

[haskell]
symbol = "  "

[hg_branch]
symbol = "  "

[java]
symbol = "  "

[julia]
symbol = "  "

[kubernetes]
disabled = false

[memory_usage]
symbol = " "
disabled = true

[nim]
symbol = " "

[nix_shell]
format = 'in [$symbol($name )]($style)'
symbol = "  "

[nodejs]
symbol = "  "

[package]
symbol = "📦 "

[php]
symbol = "  "

[python]
symbol = "  "

[ruby]
symbol = "  "

[rust]
symbol = "  "

[status]
symbol = "×"
not_executable_symbol = "∅"
not_found_symbol = "∉"
sigint_symbol = "⊥"
signal_symbol = "⋕"
disabled = true

[sudo]
symbol = "⚝  "
disabled = false

[custom.jujutsu]
symbol = "[@](green)"
format = '$symbol( $output) '
detect_folders = ['.jj']
when = "jj workspace root --ignore-working-copy --quiet"
command = """
jj \
  log \
  -r@ \
  -n1 \
  --ignore-working-copy \
  --no-graph \
  --no-pager \
  --color always \
  -T 'separate(" ",
    if(divergent,
      label("divergent", change_id.shortest(7) ++ "??"),
      change_id.shortest(7),
    ),
    if(false, bookmarks.map(|x| if(
      x.name().substr(0, 20).starts_with(x.name()),
      x.name().substr(0, 20),
      x.name().substr(0, 19) ++ "…")
    ).join(" ")),
    if(false, commit_id.shortest(7)),
    if(conflict, label("conflict", "conflict")),
    if(immutable, label("warning", "immutable")),
    if(hidden, "hidden"),
    if(!mine, "by " ++ author.name()),
    if(author.name() != committer.name() && committer.email() != "noreply@github.com", "via " ++ committer.name()),
  )'
"""

# [custom.jujutsu-closest-bookmarks]
# symbol = "[](green)"
# format = '($symbol $output )'
# detect_folders = ['.jj']
# when = "jj workspace root --ignore-working-copy --quiet"
# command = """
# jj \
#   log \
#   -r 'closest_bookmark(@)' \
#   --ignore-working-copy \
#   --no-graph \
#   --no-pager \
#   --color always \
#   -T 'bookmarks.join(" ") ++ " "'
# """
